Last touches for CI
Signed-off-by: ugm2 <unaigaraymaestre@gmail.com>

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -1,14 +1,23 @@
-name: Docker Build, Test and Publish
+name: Publish Artifact
+
+concurrency:
+  group: PublishArtifact
+  cancel-in-progress: false
 
 on:
+  workflow_dispatch:
   push:
-    branches:
-      - main
-  pull_request:
-    branches:
-      - main
+    branches: [ main ]
 
 jobs:
+  build-and-run-linting:
+    name: Run linting
+    uses: ./.github/workflows/linting.yml
+
+  build-and-run-tests:
+    name: Run tests
+    uses: ./.github/workflows/tests.yml
+
   build-test-and-publish:
     runs-on: ubuntu-latest
 
@@ -33,6 +42,39 @@ jobs:
 
       - name: Login to GitHub Container Registry
         run: echo "${{ secrets.GH_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
+
+      - name: Verify Changelog Update
+        id: verify_changelog
+        run: |
+          VERSION=$(echo "${{ env.LIB_VERSION }}" | sed 's/^v//') # Remove leading 'v' if present
+          if ! grep -q "## \[$VERSION\]" CHANGELOG.md; then
+            echo "Error: No changelog entry found for version $VERSION."
+            exit 1
+          fi
+
+      - name: Log in to the Docker registry
+        uses: docker/login-action@v1
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GH_TOKEN }}
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+
+      - name: Build and push
+        uses: docker/build-push-action@v5
+        with:
+          context: .
+          file: ./Dockerfile
+          push: ${{ github.ref == 'refs/heads/main' }}
+          tags: ghcr.io/guexit/guexit-image-generation:${{ env.LIB_VERSION }}
+          build-args: |
+            LIB_VERSION=${{ env.LIB_VERSION }}
+          secrets: |
+            GIT_CREDENTIALS=${{ secrets.GH_TOKEN }}
+          cache-from: type=registry,ref=ghcr.io/guexit/guexit-image-generation:cache
+          cache-to: type=registry,ref=ghcr.io/guexit/guexit-image-generation:cache,mode=max
 
       - name: Extract Release Notes from Changelog
         id: release_notes
